engines:
  bundler-audit:
    enabled: true
    checks:
      Insecure Source:
        enabled: false
  rubocop:
    enabled: true
    channel: rubocop-0-67
  reek:
    enabled: true
    checks:
      IrresponsibleModule/IrresponsibleModule:
        enabled: false
      UncommunicativeName/UncommunicativeVariableName:
        enabled: false
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
ratings:
  paths:
  - lib/**
  - "**.rb"
exclude_paths:
- spec/**/*
